/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HelloWorldGradle;

public class HelloWorld {
  public static void main(String[] args) {
	System.out.println("hello gradle...");
	System.out.println("hi");
}
}
